### ISSUE TITLE
Gamepad repeat

### ISSUE THREAD

**Issue by davedoesdev** [torch2424/responsive-gamepad#27]
If I keep e.g. left stick pulled right, I only get a single input change event.
How easy would it be to generate multiple input change events in this case - in the same way that a key being held down does?

**Comment by torch2424** [comment]
@davedoesdev Hello! Stoked to hear from you! Hope all is well! :smile: 

So, in order to get key repeating, It would be super easy to do. We'd essentially just have to poll the state using [`requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame):

```
let isRunning = false;

const onAnimatonFrame = () => {
  if(!isRunning) return;
  // Get the state and do stuff
  requestAnimationFrame(onAnimationFrame);
}

isRunning = true;
onAnimationFrame();

// Set isRunning to false later to cancel.
```

However, I don't know if this library is the right layer to do this :thinking: For a couple of reasons:

1. Adding a repeating function can slow down some low-end devices on the web, by clogging up the main thread of the event loop (albeit a small event but still). So I'd rather maybe just add a quick example on how to poll for the state on the README? If we do make a function for this, I don't think it should be enabled by default.

2. The library is pretty small right now, and I'd be stoked to keep it small. I know this won't be a lot of bytes, but again, I don't think it's something difficult to solve on another layer, that it needs to be solved here if that makes sense? :smile: 

Let me know what you think! Again, glad that you're still engaged on the project :+1: Thank you! :smile:

**Comment by davedoesdev** [comment]
@torch2424 yes well thanks. What have you been doing?

What you say makes sense. So essentially one wouldn't call enable()?

**Comment by torch2424** [comment]
@davedoesdev 

> What have you been doing?

Recently, I just got a new job 😄 And I'm moving soon, so just been doing a lot of life stuff. Looking forward to doing more open source soon though!

> So essentially one wouldn't call enable()?

If I remeber correctly, it would still need to be enabled, as that is what sets ups the key listeners and all that. But instead of adding callbacks to the keypresses, you would poll for the state, and then call your functions when ever something matches the state you want 👍 

Does that make sense?

**Comment by davedoesdev** [comment]
Yes, thanks and good luck!
